#!/usr/bin/env python

"""
creates local cache of instance tiddlers to be included in distribution
"""

import sys

from tiddlywebplugins.instancer.util import cache_tiddlers


def main(args):
	# TODO: automatically generate symlinks and .meta files
	cache_tiddlers("tiddlywebplugins.console")
	return True


if __name__ == "__main__":
	status = not main(sys.argv)
	sys.exit(status)
